- CHANGELOG.md
- go.mod
- go.sum
> Fix jwt-go dependency

- CHANGELOG.md
- helm/athena/templates/certs-secret.yaml
> Fix a bug in Athena certs secret

- Dockerfile
> Update alpine to 3.15

- CHANGELOG.md
- helm/athena/templates/fixjob/fixjob-rbac.yaml
See https://gigantic.slack.com/archives/C032Z9SN72N
> Fix RBAC rule for fix secret job

- CHANGELOG.md
- helm/athena/templates/pdb.yaml
> Add PodDisruptionBudget template

- .abs/main.yaml
- .ats/main.yaml
- .circleci/config.yml
- CHANGELOG.md
- helm/athena/.kube-linter.yaml
- helm/athena/Chart.yaml
- helm/athena/templates/_helpers.tpl
- helm/athena/templates/certs-secret.yaml
- helm/athena/templates/configmap.yaml
- helm/athena/templates/deployment.yaml
- helm/athena/templates/ingress.yaml
- helm/athena/templates/network-policy.yaml
- helm/athena/templates/pdb.yaml
- helm/athena/templates/pull-secret.yaml
- helm/athena/templates/rbac.yaml
- helm/athena/templates/secret.yaml
- helm/athena/templates/service.yaml
- helm/athena/values.schema.json
- helm/athena/values.yaml
- tests/ats/Pipfile
- tests/ats/Pipfile.lock
- tests/ats/test_basic_cluster.py
- tests/test-values.yaml
towards https://github.com/giantswarm/giantswarm/issues/21140
> add test coverage to athena

- .abs/main.yaml
- .circleci/config.yml
- CHANGELOG.md
- README.md
- helm/athena/Chart.yaml
Towards https://github.com/giantswarm/roadmap/issues/1097
> make athena a managed app

- helm/athena/templates/configmap.yaml
> use kindOf for provider type

- .nancy-ignore
- CHANGELOG.md
- README.md
- helm/athena/templates/configmap.yaml
Towards https://github.com/giantswarm/roadmap/issues/1163
> Enforce the management cluster name in workload cluster info

- .circleci/config.yml
- .nancy-ignore
- CHANGELOG.md
> add-to-capa-collection

- helm/athena/templates/configmap.yaml
> make configmap with missing CA look cleaner

- .circleci/config.yml
- CHANGELOG.md
> Push to openstack app collection

- CHANGELOG.md
- helm/athena/templates/fixjob/fixjob-np.yaml
> Fix typo in CiliumNetworkPolicy

- CHANGELOG.md
- README.md
Closes https://github.com/giantswarm/roadmap/issues/1603
> Remove ca pem from readme

- CHANGELOG.md
- helm/athena/templates/deployment.yaml
- helm/athena/templates/psp.yaml
- helm/athena/values.yaml
Please review whether this could be breaking.
> Add seccomp to athena.

- .circleci/config.yml
- CHANGELOG.md
towards https://github.com/giantswarm/roadmap/issues/2235
> push to kvm and capz app collections

- .circleci/config.yml
- CHANGELOG.md
> Remove shared app collection from circle CI

- CHANGELOG.md
- helm/athena/templates/pdb.yaml
Towards https://github.com/giantswarm/roadmap/issues/2298
> Changed pod disruption budget to percentage.

- CHANGELOG.md
- helm/athena/templates/configmap.yaml
- helm/athena/values.schema.json
- helm/athena/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/1712
> add api server port value for workload clusters

- CHANGELOG.md
- helm/athena/templates/psp.yaml
- helm/athena/values.schema.json
- helm/athena/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/28338
> PSP Toggle

- CHANGELOG.md
- go.mod
- go.sum
* Update module github.com/giantswarm/microerror to v0.4.1
* Update dependencies and tidy up
* Update CHANGELOG.md
---------
> Giantswarm modules test (#296)

- helm/athena/values.yaml
Disabled enforcing pod security standards by default
> Fixed default values

- README.md
> Fix CircleCI badge in README.md

- CHANGELOG.md
- pkg/graph/resolver/identity.resolvers.go
- pkg/graph/resolver/kubernetes.resolvers.go
> Resolved golangci-lint v2 problems in athena 

- .circleci/config.yml
> Bump architect-orb to v5.15.0
